version: "3.8"
services:
  web:
    build: ./app
    image: 777123362112.dkr.ecr.us-west-1.amazonaws.com/workshop2:workshop2_web # Task 5 set up Django app in deployment 02APR22 WC
    command: gunicorn nc_tutorials.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8080
    environment:
      - DB_NAME=nc_tutorials_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=nctutorials.cq098hjt3y3q.us-west-1.rds.amazonaws.com # YOUR_DB_ENDPOINT_HERE
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-50-18-35-185.us-west-1.compute.amazonaws.com # EC2 Instance Task 5 for RDS DB 02APR22 WC
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: 777123362112.dkr.ecr.us-west-1.amazonaws.com/workshop2:workshop2_nginx # Task 5 set up Django app in deployment 02APR22 WC
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      # - 8000:80
      # - 8001:80
      - 8080:80
    depends_on:
      - web
volumes:
  static_volume:
